---
version: '3.3'
services:
    application:
        build:
          context: .
        env_file: .env
        restart: on-failure
        depends_on:
            - postgresql
    postgresql:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=sukaPizdecSlozhniyParol228
        ports:
            - 5432:5432
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        image: 'bitnami/redis:latest'
        ports:
            - 6379:6379
